### ISSUE TITLE
Value.meaning() is deprecated

### ISSUE THREAD

**Issue by eamonnmcmanus** [GoogleCloudPlatform/gcloud-java#102]
[Value.meaning()](http://googlecloudplatform.github.io/gcloud-java/apidocs/com/google/gcloud/datastore/Value.html#meaning()) is deprecated, which is surprising for a new API. The reason is that it exposes datastore functionality that is slated for deletion, but which people might want to use meanwhile. I suggest that the `@deprecated` tag should include text saying explicitly that this method will be deleted at some point, and if possible giving a planned date for the deletion.

**Comment by ajkannan** [comment]
Update: the [`ValueBuilder`](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/ValueBuilder.java) interface should contain `getMeaning()` and `meaning(int meaning)`, since it's a field that gcloud-java should get and set if a value has that field set already.  For example, if a user says something like `valueLoadedFromServer.toBuilder().build();`, meaning should not be unset.  However, this necessitates the getter and setter in the `Value` builder be public.  I've added `@deprecated` tags to those methods and also made the getter (`Value.meaning()`) package scope.  Do you think that's sufficient to close this issue @eamonnmcmanus?

**Comment by eamonnmcmanus** [comment]
I think that the `ValueBuilder` methods that have the `@Deprecated` annotation should also have a javadoc comment with a `@deprecated` tag that explains why they are deprecated.

**Comment by pcostell** [comment]
We never really deprecated the field because it was never public to begin with. It's solely for compatibility with existing App engine libraries.

If you need a message for the field, I think passing through the same one on the proto is probably fine:

    The `meaning` field should only be populated for backwards compatibility.
