### ISSUE TITLE
Adding a storage example to the readme

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#164]
It would be nice to add a storage usage example in both the main and the storage READMEs.

Is there any reason for not having this that I am missing? If not, I can take care of adding it.

**Comment by aozarov** [comment]
Time is mainly the biggest reason. I suspended my work on GCS (due to higher priority issues) for providing functional blob and bucket classes (see: https://github.com/GoogleCloudPlatform/gcloud-java/compare/master...aozarov:master) which are likely to effect the usage-example and readme. 

Would you like to pull these changes from me and complete #55 (I still can't see my self working on it in the near future).

**Comment by mziccard** [comment]
Sure thing :)

**Comment by aozarov** [comment]
Fixed by #209
