### ISSUE TITLE
Lazy loading of entities when running a query

### ISSUE THREAD

**Issue by clardeur** [GoogleCloudPlatform/gcloud-java#548]
I just want to scroll all entities of a specific kind in a lazy way. I have tried to add a limit but as intended I have only the number of specified results and not the entire dataset.

```java
StructuredQuery<Entity> query = Query.entityQueryBuilder()
    .kind("user")
    .limit(100)
    .build();

QueryResults<Entity> results = datastore.run(query);
```

How to do it ? Did you plan to add a `fetchSize()` parameter ?

Without `limit()` I have a DatastoreException: Server returned an error INTERNAL 500

**Comment by ajkannan** [comment]
Hi @clardeur, thanks for reporting this issue.  Query results are already sent in batches, but it looks like the amount of data per batch is still causing you errors.  `gcloud-java` doesn't have control over the batch size; that's decided by Google Cloud Datastore.  Instead, `gcloud-java` could return you a cursor.  The reason `QueryResults.cursorAfter()` isn't already exposed is that it isn't supported for `GqlQuery`.  That support depends on Datastore v1beta3.  

/cc @aozarov @mziccard: does this look like a viable solution: we could expose a cursor for `StructuredQuery` as a stopgap measure until `cursorAfter` becomes available.  With this change, users can do something like this:

```java
StructuredQuery<Entity> query = Query.entityQueryBuilder()
    .kind("user")
    .limit(100)
    .build();
QueryResults<Entity> results = datastore.run(query);
while (results.cursorAfter() != null) {
  // do whatever you need to do with the current collection of results
  query = query.toBuilder().startCursor(results.cursorAfter()).build();
  results = datastore.run(query); // now results points to the next 100 results
}
```

@clardeur if you need a quick fix while this issue is being resolved, you could try setting `offset` in subsequent queries (instead of `limit`).  However, you can only set an offset of up to 1000 entities, and the results will be slow.

**Comment by ajkannan** [comment]
This behavior stems from a Google Cloud Datastore issue, which can be tracked [here](https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/85).

I've edited my comment above to mention that instead of introducing a new cursor, we will set `cursorAfter` to work around this issue.  Note that `cursorAfter` will be null until all the entities from the current `QueryResults` have been consumed.  I'm starting work on this issue now.

**Comment by clardeur** [comment]
@ajkannan Thanks for your quick reply and the workaround.

I understand that the batch size is a restriction from Google Cloud Datastore and you don't have the control on it but I think that as an end-user of the `gcloud-java` client, I don't want to add some boilerplate code to iterate over queries, even if it should be possible for keeping a fine-grained control.

What do you think about it ? Could you expose on the API a `ScrollQuery` with a `querySize()` parameter that would use the `limit()` and `cursorAfter() internally ?

**Comment by mziccard** [comment]
@clardeur Thanks for the reply. I think you are right, what we do elsewhere in `gcloud-java` is to also provide an `iterateAll` method that returns an iterator over the whole query result avoiding you to explicitly deal with multiple requests. That way you should be able to do something like:
```java
StructuredQuery<Entity> query = Query.entityQueryBuilder()
    .kind("user")
    .limit(100)
    .build();
QueryResults<Entity> results = datastore.run(query);
Iterator<Entity> iterator = results.iterateAll();
while (iterator.hasNext()) {
  // do something with the entity iterator.next()
}
```
How do you see this?
@ajkannan do you think this could be feasible?

**Comment by clardeur** [comment]
@mziccard the `iterateAll()` is what I need, like this I could build a Java 8 `Stream` on it. :+1:

**Comment by aozarov** [comment]
@clardeur thank you for your input.

@mziccard, I think this case is different from the other `gcloud-java` `list` operations we have so far. Here are some differences:

1) `limit` != `fetchSize` - though they sound and feel similar (and indeed one could achieve the other's goal) they are not *exactly* the same. `limit` is an SQL construct that suggests no more results after that limit are necessary whereas fetchSize/chunkSize is a batching optimization.

2) Datastore supports a row/entity-level cursor (in concept, this does not work in v1beta2 but will work in the upcoming version) where as the other services only support page level cursor. Therefore the Datastore `QueryResults` is actually *already* an iterator that is equal to `iterateAll`, where "All" means all values constrained by the query, with an ability to stop at any point and use the cursor (once available) to resume.

3) The reason `QueryResults` is an iterator (rather than, lets say, a List) is because when a result is too big it is actually returned in chunks/batches, and `gcloud-java` gets new batches as needed. Currently, the decision of what is returned in one chunk/batch is the Datastore's and depends on both results size and fetch time. Unfortunately, the Datastore has a bug, GoogleCloudPlatform/google-cloud-datastore#85, where the service fails to detect that it should stop accumulating data when batch is too big for it to handle. This bug is known to be fixed in the upcoming version of the Datastore.

I do think a user-level batch size, which the server can use to further constrain its own chunking logic,
would be nice. I suggested it to the Datastore team but I am not sure if they will implement it.

Even without having a user-configurable batch size, I would expect this not to be an issue after Datastore fixes their bug. Datastore chunking will probably be sufficient in all cases (except maybe for clients that are *very* memory constraint).

@ajkannan's suggestion above is merely a workaround to avoid the Datastore bug until its fixed and without changing the API.

Indeed, `gcloud-java` could manipulate the query's limit (if given by the user or not) to make sure that we never ask for more than X results at a time (where X is is the user-configured batch size).  This would provide a library level chunking. Even in this case, there is no need for an additional `iterateAll`; the current `iterator` could do that.  However, using the current underlying Datastore API, we will not be able implement the same approach for GQL. I asked the Datastore team for advice about that as well.

For now, I suggest that we continue with #549, as it could be used as a workaround, does not effect the API and won't stop us from making any future changes if we choose too.

@clardeur Yes, once we move to Java 8 we will likely provide a `Stream` option instead as an alternative to plain `Iterator`s. By then it is also possible that Datastore (as well as other services) will migrate to gRPC and provide streaming service calls.

**Comment by aozarov** [comment]
Laving it open at least until the underlying issue is fixed.

**Comment by clardeur** [comment]
I have tried the workaround and I get an error with the cursor.

```java
java.lang.IllegalArgumentException: content is not a valid UTF-8
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.google.gcloud.datastore.Cursor.<init>(Cursor.java:47)
	at com.google.gcloud.datastore.QueryResultsImpl.cursorAfter(QueryResultsImpl.java:104)
```

**Comment by aozarov** [comment]
Thanks clardeur@

Yes, it seems that in this case the content of the cursor bytes is not a valid UTF-8.
We will remove this restriction and work with the Datastore team to make sure we could
still create a url-safe string value for it.

**Comment by clardeur** [comment]
@aozarov ok I hope that this problem will be solved soon by the Datastore team or with this workaround because since the migration to the gcloud-java library this is a blocking point for us. 

Thanks for your envolvement.

**Comment by ajkannan** [comment]
Hi @clardeur, we added a fix for the issue (#578).  Do you need us to a new release version on Maven for this change?

**Comment by clardeur** [comment]
@ajkannan yes if it works, thanks.

**Comment by ajkannan** [comment]
Sure thing, I will make a release today.  Before I do this I want to resolve one more issue related to Datastore queries (#585).  Thanks for your patience!

**Comment by ajkannan** [comment]
Update: version 0.1.3 is now pushed and includes a fix for the `IllegalArgumentException` issue.

**Comment by clardeur** [comment]
@ajkannan tested and LGTM ;)

You can closed it if you want.

**Comment by ajkannan** [comment]
`gcloud-java-datastore` version 0.1.7 now uses v1beta3 which fixes the original problem.  This work around should no longer be needed, so I'll close this issue.

**Comment by Chinmay-Deshpande** [comment]
Hi , I want to get the total count of entities in a kind in google cloud datastore. When the entities are 5 Million the following code doesnt return the count.

private static Datastore datastore;
datastore = DatastoreOptions.getDefaultInstance().getService();
Query query = Query.newKeyQueryBuilder().setKind(kind).build();
int count = Iterators.size(datastore.run(query)); //count has the entities count

Could you please share insights/alternative?
