### ISSUE TITLE
Is StorageService.load the right name?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-java#56]
Right now, to load a Blob into a byte array, we use the `load` method:

```java
StorageService storage = ...;
bytes[] bytes = storage.load("bucket-name", "blob-name");
```

Is `load` the right verb for this? (Not saying it's wrong, just want to discuss this one here.)

Some of the options:

- **`load`** (This is what it is today)
- `download`
- `read`
- `getBytes`
- `readBytes`

**Comment by aozarov** [comment]
@jgeewax , I don't think this belongs in this milestone as as I think the answer for this API questions would benefit from a wider set of opinions.

**Comment by jgeewax** [comment]
Can you clarify why? I think this belongs here because naming stuff is something relatively easy to discuss, and would make things a bit more stable once we have outsiders using the library.

In short, I think it's worth having and resolving this discussion before a public announcement.

**Comment by aozarov** [comment]
As you can see, this issue is open for 21 days with no further comments/suggestions.
Clearly I liked "load" in this case (trying to make it clear that the complete content would be fetched and *loaded* into memory) and for that reason I names it as such.

I don't like download (which to me is more associated with save-to-disk) but I can live with read (though to me that normally is associated with a range/chunk rather than the complete content). I don't mind to change it to read (or its variants) but would that really be better? This is why I think we should wait until announced, so we can get more opinions...

**Comment by jgeewax** [comment]
Recapping the options based on your feedback:

- `load`: Seems clear about the action, it's putting stuff to memory
- `download`: I can agree that this tends to me "put to disk" so I can understand that.
- `read`: I could go either way on this, not entirely sure.
- `getBytes`: Seems like a very clear method name... I kind of like this one
- `loadBytes` wasn't on the list, but I like this too.

I still don't know if we have enough to call this discussion "closed", would love to start crossing off the different options and getting a bit of feedback.

**Comment by jboynes** [comment]
`readAllBytes` would be consistent with `java.nio.Files`

**Comment by aozarov** [comment]
I am fine with `readAllBytes`. Pull request #89

**Comment by jboynes** [comment]
Merged
