### ISSUE TITLE
Implement support for alpha features in datastore (geopt)

### ISSUE THREAD

**Issue by eddiewebb** [GoogleCloudPlatform/gcloud-java#675]
https://cloud.google.com/appengine/docs/java/datastore/geosearch is an alpha feature unusable by gcloud library since the GeoPt is not a valid property type.

I was not able to run com.google.appengine.api.datastore locally (using emulator or java-sdk), and found that using com.google.gcloud.datastore work against my gcloud datastore and sdk without hassle.

But now I am stuck unable to implement the geopt as the 2 are incompatible.

**Comment by eddiewebb** [comment]
Looks like I can accomplish what I need with RawValue -https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/Value.java#L32

**Comment by ajkannan** [comment]
Hi @eddiewebb, thanks for creating this issue.

While geospacial queries can be done via the App Engine Datastore API, they aren't yet available via the Cloud Datastore API, which is the API gcloud-java uses.  The next version of the Cloud Datastore API (v1beta3) is supposed to be released sometime soon, and soon after gcloud-java will use it and support geopoints.  

The comment you pointed out about using `RawValue` pertains more to how gcloud-java handles getting unrecognized values from Datastore, rather than enabling users to set unrecognized values.  While you can obtain geopoints from Datastore using `RawValue`, you can't create your own raw values, which may make querying difficult.  We can make this distinction clearer in the documentation.

The v1beta3 gcloud-java code, which has the classes `LatLng` and `LatLngValue` (for geopoints), is currently sitting in the `update-datastore` branch and is functional when used against that branch's local service emulator, `LocalGcdHelper`.  However, that branch can't be used to send requests to Cloud Datastore, as they do not yet service v1beta3 requests.

**Comment by eddiewebb** [comment]
Awesome, thanks @ajkannan I guess I'll just fudge it with some spherical calculations until its ready to ship.

**Comment by mziccard** [comment]
I believe this is now fixed. We added  [`LatLng`](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/main/java/com/google/cloud/datastore/LatLng.java) and [`LatLngValue`](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/main/java/com/google/cloud/datastore/LatLngValue.java) classes.
