### ISSUE TITLE
Is it possible to use ApplicationDefaultCredentials for SignUrlOption?

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/gcloud-java#701]
Currently [Storage.SignUrlOption](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-storage/src/main/java/com/google/gcloud/storage/Storage.java#L782) receives `com.google.gcloud.AuthCredentials.ServiceAccountAuthCredentials`, but how to use ApplicationDefaultAuthCredentials with that method? I think we should allow using ApplicationDefaultAuthCredentials if possible.

**Comment by tmatsuo** [comment]
I think there should be an interface for Credentials and use it as the argument, just my 2 cents

**Comment by aozarov** [comment]
Indeed as of now you can only explicitly set `com.google.gcloud.AuthCredentials.ServiceAccountAuthCredentials`.

However if you don't specify it `signUrl` may still work based on your service auth config (if it is configured with `AuthCredentials.ServiceAccountAuthCredentials` or using `ApplicationDefaultAuthCredentials` AND the default auth config is associated with a [service account](https://github.com/google/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java).

`ApplicationDefaultAuthCredentials` is not required to be associated with a service account (and provide private-key).

**Comment by tmatsuo** [comment]
Ok, thanks! I didn't know that you can not use the GCE service account for signing URL. However, isn't it appropriate for that method to receive an interface? Especially if there is a possibility that GCE service account can be used for signing in the future (I'm not sure though).


Related:
http://googlecloudplatform.github.io/gcloud-python/stable/storage-blobs.html#gcloud.storage.blob.Blob.generate_signed_url
https://github.com/GoogleCloudPlatform/gcloud-python/issues/922

**Comment by aozarov** [comment]
Yes, we could do something similar to `gcloud-python` and accept `AuthCredentials` instead of the specific `ServiceAccountAuthCredentials` but similar to the Python API this class does not expose
in its API a service-account or private key.

We could still get it and then reject any instances that are not known to us to support the signing.
I don't like that such enforcement is a run-time failure but maybe that is not *too* bad as a runtime
failure is already possible when not providing anything.
Also, I don't like that this way a user could not implement its own AuthCrendentials to work
with the signing as the signature does not specify it.

We could define a Signing interface and make some of our AuthCrendentials credentials implement it.
I am +1 for it. Is that what you are suggesting?

@ajkannan is it something that you will be interested in and have time for it?

**Comment by tmatsuo** [comment]
@aozarov Yeah, that seems a right approach!

**Comment by ajkannan** [comment]
Sure, I can take this issue.

**Comment by mziccard** [comment]
Fixed with #854
