### ISSUE TITLE
Rename class DnsRecord

### ISSUE THREAD

**Issue by mderka** [GoogleCloudPlatform/gcloud-java#779]
This was pointed out by the DNS team.

**Comment by jgeewax** [comment]
Errr - really? I don't love this... can we debate a bit more first.... ?

**Comment by mderka** [comment]
Oh, I did not realize this. We certainly can. Both Jacob and @aozarov thought that this was a good idea, and I kind of agree. I am restoring the comment in the doc and pausing here.

**Comment by mderka** [comment]
I renamed the issue. The final name is to be decided after some discussion. The suggestions are DnsRecordSet and ResourceRecordSet.

**Comment by ajkannan** [comment]
I slightly prefer DnsRecordSet over ResourceRecordSet, but I'm fine with either.  RecordSet would be shorter; do you think it's a clear enough name?

**Comment by aozarov** [comment]
> Errr - really? I don't love this... can we debate a bit more first.... ?

The issue is that what we call `DnsRecord` does not actually represent **one** DNS record but rather a set of records (and therefore is called in the underlying service API `ResourceRecordSet`).

BTW, it looks like this long name was adopted by gcloud-python though node choose Record (which I personally think is wrong).

I think the main point is to indicate that it is a set rather than an individual item and therefore my ordered preference would be: `RecordSet`, `DnsRecordSet`, `ResourceRecordSet`. 
With a much stronger preference to the first.

**Comment by mderka** [comment]
After some discussion both here and internally, including the input from the DNS team, we will rename to `RecordSet`.
