### ISSUE TITLE
Update order of after_success tasks for deployment

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#841]
We should push website and readme version updates after the artifacts have successfully been pushed.  Integration tests (part of the deployment step) sometimes fail because of flakiness, and it's wasted effort to push a new version of the website send a PR to update the readme versions when Travis will have to be rerun.

**Comment by mziccard** [comment]
`after_success.sh` is run only once the codebase has already passed unit and integration tests. Is there a value in re-running tests as part of the deployment step? In fact we skip them when deploying snapshots.

**Comment by ajkannan** [comment]
We had explicitly skip tests before, but after an incident where the Cobertura-instrumented classes were deployed rather than the actual jars, we decided to keep the tests in.

**Comment by mziccard** [comment]
The Cobertura issue was fixed by adding `clean` to the deploy command if I recall correctly. We removed the `-DskipTests=true` "just" to do a double check. I am wondering whether we should disable tests again to avoid flaky tests from interfering with artifact deployment. Also I would consider the fact that running all tests is taking more and more time due to services that do not have a local emulator.

**Comment by aozarov** [comment]
I see your point @mziccard however running the tests before deploy may have their own merits (e.g. if one remove that clean later on as "unnecessary").  What if we just disabled integration tests? -DskipITs?
Also, I think it is logical to first deploy the new artifact and only later update the docs to reflect it, no?

**Comment by ajkannan** [comment]
I'm +1 for running tests, excluding ITs
