### ISSUE TITLE
PubSub.listSubscriptions(topic) returns only names, not full subscriptions

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#978]
We need to change the signature of:
- `Page<Subscription> listSubscriptions(String topic, ListOption... options)`
- `Future<AsyncPage<Subscription>> listSubscriptionsAsync(String topic, ListOption... options);`

to:
- `Page<String> listSubscriptions(String topic, ListOption... options)`
- `Future<AsyncPage<String>> listSubscriptionsAsync(String topic, ListOption... options);`

As listing subscriptions by topic returns only names (see [here](https://cloud.google.com/pubsub/reference/rpc/google.pubsub.v1#google.pubsub.v1.ListTopicSubscriptionsResponse)). /cc @aozarov

**Comment by eschapira** [comment]
The topic owner/viewer may not have access to the subscription details; but they can see the name of the subscriptions and delete those subscriptions.

If we are using Subscription objects, as long as you don't need to fetch the details in order to instantiate it, meaning that you can instantiate a subscription object by just using the name, it should be fine to return the subscription object.

It is important to keep in mind that these subscriptions may belong to a different project.

**Comment by mziccard** [comment]
This was taken care of in #984
